theme: jekyll-theme-cayman
title: Luis Cabanillas
description: Program, Product & Project Manager and Scrum Master with solid experience in Software Development and enterprise solutions. Passionate on product innovation, and obsess over customers to deeply understand the business needs and merge technical development around customer satisfaction.
logo: prof.jpg